import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:archive/archive.dart';
import 'package:m3e_collection/m3e_collection.dart';

/// Service for exporting processed text as PDF, DOCX (TXT-based), or TXT files.
/// Provides a bottom sheet UI for format selection.
class ExportService {
  /// Sanitize text for PDF rendering — built-in PDF fonts only support Latin-1.
  /// Replace unsupported characters with a safe fallback.
  static String _sanitizeForPdf(String text) {
    final buffer = StringBuffer();
    for (final codeUnit in text.codeUnits) {
      if (codeUnit < 256) {
        buffer.writeCharCode(codeUnit);
      } else {
        buffer.write(' '); // Replace unsupported chars with space
      }
    }
    return buffer.toString();
  }

  // ──────────────────────────────────────────────
  //  EXPORT AS PDF
  // ──────────────────────────────────────────────

  /// Generate a branded PDF with optional Rewordium header and content sections.
  static Future<File?> exportAsPdf(
    String title,
    String content, {
    String? originalText,
    bool showRewordiumHeader = true,
  }) async {
    try {
      final safeTitle = _sanitizeForPdf(title);
      final safeContent = _sanitizeForPdf(content);
      final safeOriginal =
          originalText != null ? _sanitizeForPdf(originalText) : null;

      final pdf = pw.Document();
      final now = DateTime.now();
      final timestamp =
          '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} '
          '${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}';

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          header: showRewordiumHeader
              ? (context) => pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Text(
                            'Rewordium',
                            style: pw.TextStyle(
                              fontSize: 20,
                              fontWeight: pw.FontWeight.bold,
                              color: PdfColor.fromHex('#009B6E'),
                            ),
                          ),
                          pw.Text(
                            timestamp,
                            style: pw.TextStyle(
                              fontSize: 10,
                              color: PdfColor.fromHex('#718096'),
                            ),
                          ),
                        ],
                      ),
                      pw.SizedBox(height: 4),
                      pw.Divider(
                        color: PdfColor.fromHex('#E2E8F0'),
                        thickness: 1,
                      ),
                      pw.SizedBox(height: 12),
                    ],
                  )
              : null,
          footer: showRewordiumHeader
              ? (context) => pw.Column(
                    children: [
                      pw.Divider(
                        color: PdfColor.fromHex('#E2E8F0'),
                        thickness: 0.5,
                      ),
                      pw.SizedBox(height: 6),
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Text(
                            'Generated by Rewordium',
                            style: pw.TextStyle(
                              fontSize: 9,
                              color: PdfColor.fromHex('#718096'),
                            ),
                          ),
                          pw.Text(
                            'Page ${context.pageNumber} of ${context.pagesCount}',
                            style: pw.TextStyle(
                              fontSize: 9,
                              color: PdfColor.fromHex('#718096'),
                            ),
                          ),
                        ],
                      ),
                    ],
                  )
              : null,
          build: (context) {
            final widgets = <pw.Widget>[];

            // Title
            widgets.add(
              pw.Text(
                safeTitle,
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#2D3748'),
                ),
              ),
            );
            widgets.add(pw.SizedBox(height: 16));

            // Original text section (if provided)
            if (safeOriginal != null && safeOriginal.isNotEmpty) {
              widgets.add(
                pw.Container(
                  padding: const pw.EdgeInsets.all(12),
                  decoration: pw.BoxDecoration(
                    color: PdfColor.fromHex('#F7FAFC'),
                    borderRadius:
                        const pw.BorderRadius.all(pw.Radius.circular(8)),
                    border: pw.Border.all(
                      color: PdfColor.fromHex('#E2E8F0'),
                      width: 0.5,
                    ),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'Original Text',
                        style: pw.TextStyle(
                          fontSize: 11,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColor.fromHex('#718096'),
                        ),
                      ),
                      pw.SizedBox(height: 6),
                      pw.Text(
                        safeOriginal,
                        style: pw.TextStyle(
                          fontSize: 11,
                          color: PdfColor.fromHex('#4A5568'),
                          lineSpacing: 4,
                        ),
                      ),
                    ],
                  ),
                ),
              );
              widgets.add(pw.SizedBox(height: 16));
            }

            // Result section
            widgets.add(
              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  borderRadius:
                      const pw.BorderRadius.all(pw.Radius.circular(8)),
                  border: pw.Border.all(
                    color: PdfColor.fromHex('#009B6E'),
                    width: 0.8,
                  ),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      safeOriginal != null ? 'Result' : 'Content',
                      style: pw.TextStyle(
                        fontSize: 11,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColor.fromHex('#009B6E'),
                      ),
                    ),
                    pw.SizedBox(height: 6),
                    pw.Text(
                      safeContent,
                      style: pw.TextStyle(
                        fontSize: 11,
                        color: PdfColor.fromHex('#2D3748'),
                        lineSpacing: 4,
                      ),
                    ),
                  ],
                ),
              ),
            );

            return widgets;
          },
        ),
      );

      final tempDir = await getTemporaryDirectory();
      final sanitizedTitle =
          title.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
      final file = File(
          '${tempDir.path}/${sanitizedTitle}_${DateTime.now().millisecondsSinceEpoch}.pdf');
      final bytes = await pdf.save();
      await file.writeAsBytes(bytes);

      return file;
    } catch (e) {
      debugPrint('ExportService.exportAsPdf error: $e');
      return null;
    }
  }

  // ──────────────────────────────────────────────
  //  EXPORT AS TXT
  // ──────────────────────────────────────────────

  /// Generate a plain text file.
  static Future<File?> exportAsTxt(String title, String content,
      {String? originalText}) async {
    try {
      final buffer = StringBuffer();
      buffer.writeln('═' * 50);
      buffer.writeln('  REWORDIUM — $title');
      buffer.writeln('  ${DateTime.now().toIso8601String()}');
      buffer.writeln('═' * 50);
      buffer.writeln();

      if (originalText != null && originalText.isNotEmpty) {
        buffer.writeln('── Original Text ──');
        buffer.writeln(originalText);
        buffer.writeln();
      }

      buffer.writeln(originalText != null ? '── Result ──' : '── Content ──');
      buffer.writeln(content);
      buffer.writeln();
      buffer.writeln('─' * 50);
      buffer.writeln('Generated by Rewordium');

      final tempDir = await getTemporaryDirectory();
      final sanitizedTitle =
          title.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
      final file = File(
          '${tempDir.path}/${sanitizedTitle}_${DateTime.now().millisecondsSinceEpoch}.txt');
      await file.writeAsString(buffer.toString());

      return file;
    } catch (e) {
      debugPrint('ExportService.exportAsTxt error: $e');
      return null;
    }
  }

  // ──────────────────────────────────────────────
  //  EXPORT AS DOCX (simple text-based)
  // ──────────────────────────────────────────────

  /// Generate a real DOCX file using OOXML format.
  static Future<File?> exportAsDocx(String title, String content,
      {String? originalText}) async {
    try {
      final timestamp = DateTime.now().toIso8601String();

      // Build document.xml content
      final bodyParagraphs = StringBuffer();

      // Title
      bodyParagraphs.write(_docxParagraph(title, bold: true, fontSize: 28));
      bodyParagraphs.write(_docxParagraph('Generated by Rewordium — $timestamp',
          fontSize: 18, color: '888888'));
      bodyParagraphs.write(_docxParagraph(''));

      if (originalText != null && originalText.isNotEmpty) {
        bodyParagraphs
            .write(_docxParagraph('Original Text', bold: true, fontSize: 22));
        for (final line in originalText.split('\n')) {
          bodyParagraphs.write(_docxParagraph(line));
        }
        bodyParagraphs.write(_docxParagraph(''));
      }

      bodyParagraphs.write(_docxParagraph(
          originalText != null ? 'Result' : 'Content',
          bold: true,
          fontSize: 22));
      for (final line in content.split('\n')) {
        bodyParagraphs.write(_docxParagraph(line));
      }

      final documentXml =
          '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>
$bodyParagraphs
  </w:body>
</w:document>''';

      final contentTypesXml =
          '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>''';

      final relsXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>''';

      // Build ZIP archive (DOCX is a ZIP)
      final archive = Archive();
      archive
          .addFile(ArchiveFile.string('[Content_Types].xml', contentTypesXml));
      archive.addFile(ArchiveFile.string('_rels/.rels', relsXml));
      archive.addFile(ArchiveFile.string('word/document.xml', documentXml));

      final bytes = ZipEncoder().encode(archive);
      if (bytes == null) return null;

      final tempDir = await getTemporaryDirectory();
      final sanitizedTitle =
          title.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
      final file = File(
          '${tempDir.path}/${sanitizedTitle}_${DateTime.now().millisecondsSinceEpoch}.docx');
      await file.writeAsBytes(bytes);

      return file;
    } catch (e) {
      debugPrint('ExportService.exportAsDocx error: $e');
      return null;
    }
  }

  /// Helper to create a DOCX paragraph in OOXML format.
  static String _docxParagraph(String text,
      {bool bold = false, int fontSize = 20, String? color}) {
    final escapedText = text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
    final runProps = StringBuffer('<w:rPr>');
    runProps.write('<w:sz w:val="$fontSize"/><w:szCs w:val="$fontSize"/>');
    if (bold) runProps.write('<w:b/>');
    if (color != null) runProps.write('<w:color w:val="$color"/>');
    runProps.write('</w:rPr>');
    return '    <w:p><w:r>$runProps<w:t xml:space="preserve">$escapedText</w:t></w:r></w:p>\n';
  }

  // ──────────────────────────────────────────────
  //  SHARE FILE
  // ──────────────────────────────────────────────

  /// Share a file using the system share sheet.
  static Future<void> shareFile(File file, {String? subject}) async {
    try {
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: subject,
      );
    } catch (e) {
      debugPrint('ExportService.shareFile error: $e');
    }
  }

  // ──────────────────────────────────────────────
  //  EXPORT BOTTOM SHEET UI
  // ──────────────────────────────────────────────

  /// Show a bottom sheet with export format options.
  /// Returns when the export is complete or cancelled.
  static Future<void> showExportSheet(
    BuildContext context, {
    required String title,
    required String content,
    String? originalText,
    bool showRewordiumHeader = true,
  }) async {
    return showModalBottomSheet<void>(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (context) => _ExportBottomSheet(
        title: title,
        content: content,
        originalText: originalText,
        showRewordiumHeader: showRewordiumHeader,
      ),
    );
  }
}

// ──────────────────────────────────────────────────
//  EXPORT BOTTOM SHEET WIDGET
// ──────────────────────────────────────────────────

class _ExportBottomSheet extends StatefulWidget {
  final String title;
  final String content;
  final String? originalText;
  final bool showRewordiumHeader;

  const _ExportBottomSheet({
    required this.title,
    required this.content,
    this.originalText,
    this.showRewordiumHeader = true,
  });

  @override
  State<_ExportBottomSheet> createState() => _ExportBottomSheetState();
}

class _ExportBottomSheetState extends State<_ExportBottomSheet> {
  bool _isExporting = false;
  String? _exportingFormat;

  Future<void> _export(String format) async {
    setState(() {
      _isExporting = true;
      _exportingFormat = format;
    });

    File? file;
    switch (format) {
      case 'pdf':
        file = await ExportService.exportAsPdf(
          widget.title,
          widget.content,
          originalText: widget.originalText,
          showRewordiumHeader: widget.showRewordiumHeader,
        );
        break;
      case 'docx':
        file = await ExportService.exportAsDocx(
          widget.title,
          widget.content,
          originalText: widget.originalText,
        );
        break;
      case 'txt':
        file = await ExportService.exportAsTxt(
          widget.title,
          widget.content,
          originalText: widget.originalText,
        );
        break;
    }

    if (!mounted) return;
    setState(() {
      _isExporting = false;
      _exportingFormat = null;
    });

    if (file != null && mounted) {
      final filePath = file.path;
      final title = widget.title;
      Navigator.pop(context);
      await ExportService.shareFile(File(filePath), subject: title);
    } else if (file == null && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('Export failed. Please try again.'),
          backgroundColor: Theme.of(context).colorScheme.error,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surface,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(20)),
      ),
      padding: const EdgeInsets.fromLTRB(20, 12, 20, 32),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle
          Container(
            width: 36,
            height: 5,
            decoration: BoxDecoration(
              color: Theme.of(context)
                  .colorScheme
                  .onSurfaceVariant
                  .withValues(alpha: 0.3),
              borderRadius: BorderRadius.circular(3),
            ),
          ),
          const SizedBox(height: 20),

          // Title
          Text(
            'Export As',
            style: Theme.of(context).textTheme.titleLarge!,
          ),
          const SizedBox(height: 4),
          Text(
            'Choose a format to export your results',
            style: Theme.of(context).textTheme.bodySmall!.copyWith(
                  color: Theme.of(context).colorScheme.onSurfaceVariant,
                ),
          ),
          const SizedBox(height: 24),

          // Export options
          _buildExportOption(
            icon: CupertinoIcons.doc_richtext,
            label: 'PDF Document',
            subtitle: 'Branded PDF with Rewordium header',
            color: const Color(0xFFE53935),
            format: 'pdf',
          ),
          const SizedBox(height: 12),
          _buildExportOption(
            icon: CupertinoIcons.doc_text,
            label: 'Word Document',
            subtitle: 'Compatible with Microsoft Word',
            color: const Color(0xFF1E3A8A),
            format: 'docx',
          ),
          const SizedBox(height: 12),
          _buildExportOption(
            icon: CupertinoIcons.doc_plaintext,
            label: 'Plain Text',
            subtitle: 'Simple text file (.txt)',
            color: Theme.of(context).colorScheme.onSurfaceVariant,
            format: 'txt',
          ),

          const SizedBox(height: 20),

          // Cancel button
          SizedBox(
            width: double.infinity,
            height: 48,
            child: OutlinedButton(
              onPressed: _isExporting ? null : () => Navigator.pop(context),
              style: OutlinedButton.styleFrom(
                side: BorderSide(
                  color: Theme.of(context)
                      .colorScheme
                      .onSurfaceVariant
                      .withValues(alpha: 0.3),
                ),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
              ),
              child: Text(
                'Cancel',
                style: TextStyle(
                  color: Theme.of(context).colorScheme.onSurfaceVariant,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildExportOption({
    required IconData icon,
    required String label,
    required String subtitle,
    required Color color,
    required String format,
  }) {
    final isLoading = _isExporting && _exportingFormat == format;

    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: _isExporting ? null : () => _export(format),
        borderRadius: BorderRadius.circular(16),
        child: Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: Theme.of(context)
                  .colorScheme
                  .onSurfaceVariant
                  .withValues(alpha: 0.15),
            ),
          ),
          child: Row(
            children: [
              Container(
                width: 44,
                height: 44,
                decoration: BoxDecoration(
                  color: color.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: isLoading
                    ? Padding(
                        padding: const EdgeInsets.all(8),
                        child: LoadingIndicatorM3E(
                          color: color,
                          constraints:
                              BoxConstraints(maxWidth: 24, maxHeight: 24),
                        ),
                      )
                    : Icon(icon, color: color, size: 22),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      label,
                      style: Theme.of(context).textTheme.bodyMedium!.copyWith(
                            fontWeight: FontWeight.w600,
                          ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      subtitle,
                      style: Theme.of(context).textTheme.bodySmall!.copyWith(
                            color:
                                Theme.of(context).colorScheme.onSurfaceVariant,
                            fontSize: 12,
                          ),
                    ),
                  ],
                ),
              ),
              Icon(
                CupertinoIcons.chevron_right,
                color: Theme.of(context)
                    .colorScheme
                    .onSurfaceVariant
                    .withValues(alpha: 0.5),
                size: 18,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
