import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../theme/app_theme.dart';

/// Service for exporting processed text as PDF, DOCX (TXT-based), or TXT files.
/// Provides a bottom sheet UI for format selection.
class ExportService {
  // ──────────────────────────────────────────────
  //  EXPORT AS PDF
  // ──────────────────────────────────────────────

  /// Generate a branded PDF with Rewordium header and content sections.
  static Future<File?> exportAsPdf(
    String title,
    String content, {
    String? originalText,
  }) async {
    try {
      final pdf = pw.Document();
      final now = DateTime.now();
      final timestamp =
          '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} '
          '${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}';

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          header: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'Rewordium',
                    style: pw.TextStyle(
                      fontSize: 20,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColor.fromHex('#009B6E'),
                    ),
                  ),
                  pw.Text(
                    timestamp,
                    style: pw.TextStyle(
                      fontSize: 10,
                      color: PdfColor.fromHex('#718096'),
                    ),
                  ),
                ],
              ),
              pw.SizedBox(height: 4),
              pw.Divider(
                color: PdfColor.fromHex('#E2E8F0'),
                thickness: 1,
              ),
              pw.SizedBox(height: 12),
            ],
          ),
          footer: (context) => pw.Column(
            children: [
              pw.Divider(
                color: PdfColor.fromHex('#E2E8F0'),
                thickness: 0.5,
              ),
              pw.SizedBox(height: 6),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'Generated by Rewordium',
                    style: pw.TextStyle(
                      fontSize: 9,
                      color: PdfColor.fromHex('#718096'),
                    ),
                  ),
                  pw.Text(
                    'Page ${context.pageNumber} of ${context.pagesCount}',
                    style: pw.TextStyle(
                      fontSize: 9,
                      color: PdfColor.fromHex('#718096'),
                    ),
                  ),
                ],
              ),
            ],
          ),
          build: (context) {
            final widgets = <pw.Widget>[];

            // Title
            widgets.add(
              pw.Text(
                title,
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#2D3748'),
                ),
              ),
            );
            widgets.add(pw.SizedBox(height: 16));

            // Original text section (if provided)
            if (originalText != null && originalText.isNotEmpty) {
              widgets.add(
                pw.Container(
                  padding: const pw.EdgeInsets.all(12),
                  decoration: pw.BoxDecoration(
                    color: PdfColor.fromHex('#F7FAFC'),
                    borderRadius:
                        const pw.BorderRadius.all(pw.Radius.circular(8)),
                    border: pw.Border.all(
                      color: PdfColor.fromHex('#E2E8F0'),
                      width: 0.5,
                    ),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'Original Text',
                        style: pw.TextStyle(
                          fontSize: 11,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColor.fromHex('#718096'),
                        ),
                      ),
                      pw.SizedBox(height: 6),
                      pw.Text(
                        originalText,
                        style: pw.TextStyle(
                          fontSize: 11,
                          color: PdfColor.fromHex('#4A5568'),
                          lineSpacing: 4,
                        ),
                      ),
                    ],
                  ),
                ),
              );
              widgets.add(pw.SizedBox(height: 16));
            }

            // Result section
            widgets.add(
              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  borderRadius:
                      const pw.BorderRadius.all(pw.Radius.circular(8)),
                  border: pw.Border.all(
                    color: PdfColor.fromHex('#009B6E'),
                    width: 0.8,
                  ),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      originalText != null ? 'Result' : 'Content',
                      style: pw.TextStyle(
                        fontSize: 11,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColor.fromHex('#009B6E'),
                      ),
                    ),
                    pw.SizedBox(height: 6),
                    pw.Text(
                      content,
                      style: pw.TextStyle(
                        fontSize: 11,
                        color: PdfColor.fromHex('#2D3748'),
                        lineSpacing: 4,
                      ),
                    ),
                  ],
                ),
              ),
            );

            return widgets;
          },
        ),
      );

      final tempDir = await getTemporaryDirectory();
      final sanitizedTitle =
          title.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
      final file = File(
          '${tempDir.path}/${sanitizedTitle}_${DateTime.now().millisecondsSinceEpoch}.pdf');
      final bytes = await pdf.save();
      await file.writeAsBytes(bytes);

      return file;
    } catch (e) {
      debugPrint('ExportService.exportAsPdf error: $e');
      return null;
    }
  }

  // ──────────────────────────────────────────────
  //  EXPORT AS TXT
  // ──────────────────────────────────────────────

  /// Generate a plain text file.
  static Future<File?> exportAsTxt(String title, String content,
      {String? originalText}) async {
    try {
      final buffer = StringBuffer();
      buffer.writeln('═' * 50);
      buffer.writeln('  REWORDIUM — $title');
      buffer.writeln('  ${DateTime.now().toIso8601String()}');
      buffer.writeln('═' * 50);
      buffer.writeln();

      if (originalText != null && originalText.isNotEmpty) {
        buffer.writeln('── Original Text ──');
        buffer.writeln(originalText);
        buffer.writeln();
      }

      buffer.writeln(originalText != null ? '── Result ──' : '── Content ──');
      buffer.writeln(content);
      buffer.writeln();
      buffer.writeln('─' * 50);
      buffer.writeln('Generated by Rewordium');

      final tempDir = await getTemporaryDirectory();
      final sanitizedTitle =
          title.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
      final file = File(
          '${tempDir.path}/${sanitizedTitle}_${DateTime.now().millisecondsSinceEpoch}.txt');
      await file.writeAsString(buffer.toString());

      return file;
    } catch (e) {
      debugPrint('ExportService.exportAsTxt error: $e');
      return null;
    }
  }

  // ──────────────────────────────────────────────
  //  EXPORT AS DOCX (simple text-based)
  // ──────────────────────────────────────────────

  /// Generate a DOCX-style file.
  /// Uses a simple XML structure compatible with Word.
  static Future<File?> exportAsDocx(String title, String content,
      {String? originalText}) async {
    try {
      // For now, export as rich-text formatted TXT with .docx extension
      // Full DOCX generation requires template — we use simple approach
      final buffer = StringBuffer();
      buffer.writeln('REWORDIUM — $title');
      buffer.writeln('Generated: ${DateTime.now().toIso8601String()}');
      buffer.writeln();

      if (originalText != null && originalText.isNotEmpty) {
        buffer.writeln('ORIGINAL TEXT:');
        buffer.writeln(originalText);
        buffer.writeln();
      }

      buffer.writeln(originalText != null ? 'RESULT:' : 'CONTENT:');
      buffer.writeln(content);

      final tempDir = await getTemporaryDirectory();
      final sanitizedTitle =
          title.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
      final file = File(
          '${tempDir.path}/${sanitizedTitle}_${DateTime.now().millisecondsSinceEpoch}.docx');
      await file.writeAsString(buffer.toString());

      return file;
    } catch (e) {
      debugPrint('ExportService.exportAsDocx error: $e');
      return null;
    }
  }

  // ──────────────────────────────────────────────
  //  SHARE FILE
  // ──────────────────────────────────────────────

  /// Share a file using the system share sheet.
  static Future<void> shareFile(File file, {String? subject}) async {
    try {
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: subject,
      );
    } catch (e) {
      debugPrint('ExportService.shareFile error: $e');
    }
  }

  // ──────────────────────────────────────────────
  //  EXPORT BOTTOM SHEET UI
  // ──────────────────────────────────────────────

  /// Show a bottom sheet with export format options.
  /// Returns when the export is complete or cancelled.
  static Future<void> showExportSheet(
    BuildContext context, {
    required String title,
    required String content,
    String? originalText,
  }) async {
    return showModalBottomSheet<void>(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (context) => _ExportBottomSheet(
        title: title,
        content: content,
        originalText: originalText,
      ),
    );
  }
}

// ──────────────────────────────────────────────────
//  EXPORT BOTTOM SHEET WIDGET
// ──────────────────────────────────────────────────

class _ExportBottomSheet extends StatefulWidget {
  final String title;
  final String content;
  final String? originalText;

  const _ExportBottomSheet({
    required this.title,
    required this.content,
    this.originalText,
  });

  @override
  State<_ExportBottomSheet> createState() => _ExportBottomSheetState();
}

class _ExportBottomSheetState extends State<_ExportBottomSheet> {
  bool _isExporting = false;
  String? _exportingFormat;

  Future<void> _export(String format) async {
    setState(() {
      _isExporting = true;
      _exportingFormat = format;
    });

    File? file;
    switch (format) {
      case 'pdf':
        file = await ExportService.exportAsPdf(
          widget.title,
          widget.content,
          originalText: widget.originalText,
        );
        break;
      case 'docx':
        file = await ExportService.exportAsDocx(
          widget.title,
          widget.content,
          originalText: widget.originalText,
        );
        break;
      case 'txt':
        file = await ExportService.exportAsTxt(
          widget.title,
          widget.content,
          originalText: widget.originalText,
        );
        break;
    }

    setState(() {
      _isExporting = false;
      _exportingFormat = null;
    });

    if (file != null && mounted) {
      Navigator.pop(context);
      await ExportService.shareFile(file, subject: widget.title);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: AppTheme.cardColor,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(20)),
      ),
      padding: const EdgeInsets.fromLTRB(20, 12, 20, 32),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle
          Container(
            width: 36,
            height: 5,
            decoration: BoxDecoration(
              color: AppTheme.textSecondaryColor.withOpacity(0.3),
              borderRadius: BorderRadius.circular(3),
            ),
          ),
          const SizedBox(height: 20),

          // Title
          Text(
            'Export As',
            style: AppTheme.headingSmall,
          ),
          const SizedBox(height: 4),
          Text(
            'Choose a format to export your results',
            style: AppTheme.bodySmall.copyWith(
              color: AppTheme.textSecondaryColor,
            ),
          ),
          const SizedBox(height: 24),

          // Export options
          _buildExportOption(
            icon: CupertinoIcons.doc_richtext,
            label: 'PDF Document',
            subtitle: 'Branded PDF with Rewordium header',
            color: const Color(0xFFE53935),
            format: 'pdf',
          ),
          const SizedBox(height: 12),
          _buildExportOption(
            icon: CupertinoIcons.doc_text,
            label: 'Word Document',
            subtitle: 'Compatible with Microsoft Word',
            color: const Color(0xFF1E3A8A),
            format: 'docx',
          ),
          const SizedBox(height: 12),
          _buildExportOption(
            icon: CupertinoIcons.doc_plaintext,
            label: 'Plain Text',
            subtitle: 'Simple text file (.txt)',
            color: AppTheme.textSecondaryColor,
            format: 'txt',
          ),

          const SizedBox(height: 20),

          // Cancel button
          SizedBox(
            width: double.infinity,
            height: 48,
            child: OutlinedButton(
              onPressed: _isExporting ? null : () => Navigator.pop(context),
              style: OutlinedButton.styleFrom(
                side: BorderSide(
                  color: AppTheme.textSecondaryColor.withOpacity(0.3),
                ),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
              ),
              child: Text(
                'Cancel',
                style: TextStyle(
                  color: AppTheme.textSecondaryColor,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildExportOption({
    required IconData icon,
    required String label,
    required String subtitle,
    required Color color,
    required String format,
  }) {
    final isLoading = _isExporting && _exportingFormat == format;

    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: _isExporting ? null : () => _export(format),
        borderRadius: BorderRadius.circular(16),
        child: Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: AppTheme.textSecondaryColor.withOpacity(0.15),
            ),
          ),
          child: Row(
            children: [
              Container(
                width: 44,
                height: 44,
                decoration: BoxDecoration(
                  color: color.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: isLoading
                    ? Padding(
                        padding: const EdgeInsets.all(12),
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          valueColor: AlwaysStoppedAnimation<Color>(color),
                        ),
                      )
                    : Icon(icon, color: color, size: 22),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      label,
                      style: AppTheme.bodyMedium.copyWith(
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      subtitle,
                      style: AppTheme.bodySmall.copyWith(
                        color: AppTheme.textSecondaryColor,
                        fontSize: 12,
                      ),
                    ),
                  ],
                ),
              ),
              Icon(
                CupertinoIcons.chevron_right,
                color: AppTheme.textSecondaryColor.withOpacity(0.5),
                size: 18,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
