// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.
// For more information, see: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVe43ZwiW9bGGEzcCVnof-kclVSP5swM',
    appId: '1:764897323980:web:7d6b2467c9053de4784b69',
    messagingSenderId: '764897323980',
    projectId: 'yc-startup-yc',
    authDomain: 'yc-startup-yc.firebaseapp.com',
    storageBucket: 'yc-startup-yc.firebasestorage.app',
    measurementId: 'G-W0HBDG5QEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoG1w3GaQVy2O6kjp-ZQw09TZgbUWjrTg',
    appId: '1:1046215732414:android:a97ddde5e4953c46ab02ef',
    messagingSenderId: '1046215732414',
    projectId: 'rewordium',
    storageBucket: 'rewordium.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMWvzCADRniAvuaHl1hovD-C-e1rxbe8Q',
    appId: '1:1046215732414:ios:4aec838aaf3ddae4ab02ef',
    messagingSenderId: '1046215732414',
    projectId: 'rewordium',
    storageBucket: 'rewordium.firebasestorage.app',
    iosClientId: '1046215732414-dcm9ivr4tum4unhsc37truln5ud8lpb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ycStartup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Db3MeZm2ec8OkkkypIYaxSBWWdLwmGI',
    appId: '1:764897323980:ios:ceae35d06a44ccb8784b69',
    messagingSenderId: '764897323980',
    projectId: 'yc-startup-yc',
    storageBucket: 'yc-startup-yc.firebasestorage.app',
    androidClientId: '764897323980-anii47i8t0tl42ghjbe5noq94knno3pc.apps.googleusercontent.com',
    iosClientId: '764897323980-6asarl1va57k8omfcoghefb7r2lfnrh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ycStartup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMVe43ZwiW9bGGEzcCVnof-kclVSP5swM',
    appId: '1:764897323980:web:a9dcb62add54673f784b69',
    messagingSenderId: '764897323980',
    projectId: 'yc-startup-yc',
    authDomain: 'yc-startup-yc.firebaseapp.com',
    storageBucket: 'yc-startup-yc.firebasestorage.app',
    measurementId: 'G-EGWKTMGRZP',
  );

}