// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.
// For more information, see: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This is a placeholder. Replace with your actual Firebase configuration
    return const FirebaseOptions(
      apiKey: 'YOUR_API_KEY',
      appId: 'YOUR_APP_ID',
      messagingSenderId: 'YOUR_SENDER_ID',
      projectId: 'YOUR_PROJECT_ID',
      authDomain: 'YOUR_AUTH_DOMAIN',
      storageBucket: 'YOUR_STORAGE_BUCKET',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVe43ZwiW9bGGEzcCVnof-kclVSP5swM',
    appId: '1:764897323980:web:7d6b2467c9053de4784b69',
    messagingSenderId: '764897323980',
    projectId: 'yc-startup-yc',
    authDomain: 'yc-startup-yc.firebaseapp.com',
    storageBucket: 'yc-startup-yc.firebasestorage.app',
    measurementId: 'G-W0HBDG5QEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_plUk1hp7t3YWrpsFUevGb9vCr3jC3E',
    appId: '1:764897323980:android:64562bc359208814784b69',
    messagingSenderId: '764897323980',
    projectId: 'yc-startup-yc',
    storageBucket: 'yc-startup-yc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Db3MeZm2ec8OkkkypIYaxSBWWdLwmGI',
    appId: '1:764897323980:ios:ceae35d06a44ccb8784b69',
    messagingSenderId: '764897323980',
    projectId: 'yc-startup-yc',
    storageBucket: 'yc-startup-yc.firebasestorage.app',
    iosBundleId: 'com.example.ycStartup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Db3MeZm2ec8OkkkypIYaxSBWWdLwmGI',
    appId: '1:764897323980:ios:ceae35d06a44ccb8784b69',
    messagingSenderId: '764897323980',
    projectId: 'yc-startup-yc',
    storageBucket: 'yc-startup-yc.firebasestorage.app',
    iosBundleId: 'com.example.ycStartup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMVe43ZwiW9bGGEzcCVnof-kclVSP5swM',
    appId: '1:764897323980:web:f2e0aa09380f5eb7784b69',
    messagingSenderId: '764897323980',
    projectId: 'yc-startup-yc',
    authDomain: 'yc-startup-yc.firebaseapp.com',
    storageBucket: 'yc-startup-yc.firebasestorage.app',
    measurementId: 'G-270M65FBSE',
  );
}
